# Generated by Django 4.2.14 on 2024-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=200)),
                ('endereco', models.TextField(max_length=200)),
                ('valor_divida', models.DecimalField(decimal_places=2, max_digits=2)),
                ('foto', models.ImageField(upload_to='static/fotos')),
            ],
        ),
    ]
